spring:
  config:
    activate:
      on-profile: dev
  devtools:
    add-properties: true
  datasource:
    url: jdbc:postgresql://postgres:5432/ecommerce
    username: dummy
    password: dummy
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none

# application-dev.yml
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
openapi:
  service:
    api-docs: ecommerce 
    server: http://localhost:${server.port}
    title: ecommerce 
    version: 0.0.1

jwt:
  secretKey: dummy 
